[package]
name = "api-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.9"
tonic = "0.11"
prost = "0.12"
async-graphql = "7.0.2"
async-graphql-rocket = "7.0.2"
rocket = "0.5.0"

[build-dependencies]
tonic-build = "0.11"
